rules: /usr/lib/libprologin2014.so
verbose: 3
clients:
  - ./arrogant/champion.so
  - ./noop/champion.so
  - ./silent/champion.so
  - ./current/champion.so
names:
  - Player 1
  - Player 2
  - Player 3
  - Player 4
spectators:
  - /usr/share/stechec2/prologin2014/gui/gui.so
